[project]
name = "gui"
version = "0.1.0"
description = "Web-based GUI for radioisotope identification (RIID) with the NSIL-MCA-DPP4SiPM DAQ system."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ai-edge-litert>=2.1.6",
    "nicegui>=3.14.0",
    "numpy>=2.5.0",
    "python-api",
    "scikit-learn>=1.9.0",
]

[dependency-groups]
docs = [
    "lazydocs>=0.4.8",
]
viz = [
    "tensorflow>=2.21.0",
    "tf-keras>=2.21.0",
    "visualkeras>=0.2.0",
]

[tool.uv]
package = true

[tool.setuptools]
package-dir = {"" = "."}

[tool.uv.sources]
python-api = { workspace = true }
